sudo: true
language: elixir
elixir:
  - 1.10.4
otp_release:
  - 23.0.3
matrix:
  include:
    - elixir: 1.10.4
      otp_release: 23.0.3
script:
  - mix analyze --non-interactive
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
